# 比较MXNet和TensorFlow的基础操作
需要安装的库如下：
- MXNet
- TensorFlow
- Numpy

In [1]:
import mxnet as mx
import tensorflow as tf
import numpy as np

d:\Program Files\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\util\tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))


接下来比较MX和TF创建变量时能否接受类型
- MXNet在创建张量时就能够接受类型
- tf.Variable不能接受类型，类型根据初始值来定，且不可改变，通过相应函数改变类型会使变量变成张量

In [34]:
# float32 is used by default
a = mx.nd.array([1,2,3])
# create an int32 array
b = mx.nd.array([1,2,3], dtype=np.int32)
# create a 16-bit float array
c = mx.nd.array([1.2, 2.3], dtype=np.float16)
(a.dtype, b.dtype, c.dtype,d.type)

AttributeError: 'NDArray' object has no attribute 'type'

In [26]:
a = tf.Variable(tf.eye(2,2),name='a')
b = tf.Variable(tf.zeros([2,3],dtype=tf.float16),name='b')
c = tf.to_int32(a)
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run([a,b,c]))
    a=tf.to_double(a)
    print(sess.run(a))
    print(a,b,c)

[array([[ 1.,  0.],
       [ 0.,  1.]], dtype=float32), array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float16), array([[1, 0],
       [0, 1]])]
[[ 1.  0.]
 [ 0.  1.]]
Tensor("ToDouble_2:0", shape=(2, 2), dtype=float64) <tf.Variable 'b_7:0' shape=(2, 3) dtype=float16_ref> Tensor("ToInt32_5:0", shape=(2, 2), dtype=int32)


MXNet有数种方法可以产生placeholder的效果，而tf也可以通过tf.variable或者tf.placeholder完成placeholder的效果。但是MXNet的用法更像是平时C或者Matlab里变量的用法，即什么都可以干，可以是variable，也可以是constant，也可以是placeholder
- tf.placeholder可以指定shape也可以不指定，像神经网络里时可以指定列数但不指定行数
- tf.placeholder在使用是一定要feed数据，否则会报错
- tf.placeholder不能接受一个tf.tensor对象，必须是python对象、numpy或者tensorhandle
- mx和tf中数据类型不同时均不能直接计算

In [27]:
# create a 2-dimensional array full of zeros with shape (2,3)
a = mx.nd.zeros((2,3))
# create a same shape array full of ones
b = mx.nd.ones((2,3))
# create a same shape array with all elements set to 7
c = mx.nd.full((2,3), 7)
# create a same shape whose initial content is random and
# depends on the state of the memory
d = mx.nd.empty((2,3))

In [41]:
a = tf.placeholder(tf.float16,shape=(None,3))
b = np.random.random([2,3])
print(type(b))
c = tf.to_float(a)+b
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a:b}))

<class 'numpy.ndarray'>
[[ 0.19419721  0.50434005  1.90043592]
 [ 1.34005737  0.66710633  0.43237439]]
